---
- name: "Deploy laravel_demo laravel app"
  hosts: cho_y
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  vars:
    ansistrano_git_repo: "https://github.com/nguyenky/current.git"
    ansistrano_deploy_to: "/var/www/kyln"
    ansistrano_keep_releases: 3
    # There seems to be an issue with rsync in vagrant
    ansistrano_deploy_via: copy
  roles:
    - { role: ansistrano.deploy }
