---
- hosts: gg_server_jenkins
  become: yes
  become_user: lenguyenky
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Ping
      ping:

    - name: Apt update
      shell: apt-get update