---
- hosts: gg_server_jenkins
  become: yes
  become_user: lenguyenky
  sudo: yes
  gather_facts: no
  tasks:
    - name: Ping
      ping:

    - name: install essential packages
      apt:
        name: "{{ system_packages }}"
        update_cache: yes
      vars:
        system_packages:
          - nano
          # - lsof
          # - git
          # - zip
          # - htop
          # - wget
          # - curl
          # - iotop
          # - unzip
          # - nginx
          # - php7.2-fpm