---
- hosts: gg_server_jenkins
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Ping
      ping:

    - name: Add repository for PHP
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: install essential packages
      apt:
        name: "{{ system_packages }}"
        update_cache: yes
      vars:
        system_packages:
          - nano
          - lsof
          - git
          - zip
          - htop
          - wget
          - curl
          - iotop
          - unzip
          - nginx
          - php7.2-fpm

    - shell: php --version
      register: shell_result

    - debug:
        var: shell_result.stdout_lines

    - name: Install PHP packages
      apt:
        name:
          - php7.2-gd
          - php7.2-intl
          - php7.2-xsl
          - php7.2-xml
          - php7.2-mbstring
        state: latest

    - name: Install Composer
      shell: apt install composer -y

    - name: create deploy directory
      file:
        path: "/var/www/kyln"
        state: "directory" 
        owner: "root"
        group: "root"
        mode: 0755

    - name: copy nginx config file to remote
      copy:
        src: "miscellaneous/kyln"
        dest: "/etc/nginx/sites-available/kyln"
        owner: "root"
        group: "root"
        mode: 0644

    - name: link nginx file
      file:
        src: "/etc/nginx/sites-available/kyln"
        dest: "/etc/nginx/sites-enabled/kyln"
        state: link