---
- hosts: gg_server_jenkins
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Ping
      ping:

    - name: Install python software properties
      shell: apt install -y python-software-properties
    
    - name: Add repository for PHP
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: install essential packages
      apt:
        name: "{{ system_packages }}"
        update_cache: yes
      vars:
        system_packages:
          - nano
          - lsof
          - git
          - zip
          - htop
          - wget
          - curl
          - iotop
          - unzip
          # - nginx
          # - php7.2-fpm