---
- hosts: gg_server_jenkins
  # become: yes
  # become_user: lenguyenky
  # become_method: sudo
  gather_facts: false
  tasks:
    - name: Ping
      ping:

    - name: Install python software properties
      shell: apt install -y python-software-properties